_core:
  default_config_hash: l23AWlsVwlhblRhggKqahd8SBZzQDs5_GsFuCKgDItg
exclude_paths: "/contextual/*\r\n/toolbar/*\r\n/edit/*\r\n*.js\r\n*.css"
intercept_redirects: false
purge_on_cache_clear: true
active_toolbar_items:
  configs: configs
  events: events
  extensions: extensions
  forms: forms
  frontend: frontend
  request: request
  routing: routing
  services: services
  theme: theme
  user: user
  views: views
  ajax: '0'
  assets: '0'
  blocks: '0'
  cache: '0'
  database: '0'
  devel: '0'
  http: '0'
  mail: '0'
  memory: '0'
  state: '0'
  time: '0'
  translations: '0'
query_sort: source
query_highlight: 5
ide: 'phpstorm://open?file=%f&line=%l'
ide_remote_path: ''
ide_local_path: ''
