name: Deploy to Pantheon
on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: Build and push to Pantheon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: setup-runner
        name: Setup Runner
        uses: ./.github/workflows/actions/setup-runner
        with:
          pantheon_ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
          ssh_config: ${{ secrets.SSH_CONFIG }}
          pantheon_machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
          php_version: "8.1"
          composer_version: "v2"
          terminus_version: "^2.0"
          node_version: "10.x"

      - name: Composer Install Dependencies
        run: composer install --optimize-autoloader --no-dev --prefer-dist --no-progress --no-suggest

      ## Build Theme
      - name: Build Theme Artifacts
        run: |
          cd web/themes/custom/react_hello
          npm install
      ## Prepare for Pantheon
      - name: Prepare for Pantheon
        run: |
          cp .gitignore.pantheon .gitignore
          find ./web -type d -name ".git" | xargs rm -fr
      ## Deploy
      - name: Deploy to Pantheon
        env:
          pantheon_site: "d10live"
          pantheon_env: "dev"
        run: |
          commit_message=$(git log -1 --pretty=%B)
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          terminus build:env:push $pantheon_site.$pantheon_env --message="${{ github.actor }}: CI Deployment for: $commit_message"
      ## Terminus
      - name: Terminus Drush Updates
        env:
          pantheon_site: "d10live"
          pantheon_env: "dev"
        run: |
          terminus -n drush $pantheon_site.$pantheon_env -- deploy -y
          terminus -n env:clear-cache $pantheon_site.$pantheon_env
