name: Deploy master to Pantheon
on:
  push:
    branches:
      - "dev"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_PRIVATE_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Installing Terminus
        uses: kopepasah/setup-pantheon-terminus@master
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
      - name: deployer
        env:
          pantheon_repo: "${{ secrets.PANTHEON_REPO_URL }}"
          pantheon_site_name: "${{ secrets.PANTHEON_SITE_NAME }}"
        run: |
          BASE_BRANCH=${GITHUB_REF##*/}
          git remote add pantheon $pantheon_repo
          git push -u pantheon HEAD:refs/heads/$BASE_BRANCH
          terminus multidev:create $pantheon_site_name.dev $BASE_BRANCH
