name: Build and deploy to pantheon

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Use ssh-keygen to generate ssh key
      # Convert the ssh key to PEM format using ssh-keygen -p -m PEM -f [NAME_OF_SSH_KEY_PLACEHOLDER]
      # Add private key to repository secret
      # Add publick key to the server where you want to deploy, in this case pantheon
      # Ref https://medium.com/swlh/pantheon-and-github-actions-automated-deployments-via-github-actions-c245aa954797
      - name: Add ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_PRIVATE_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}
      - name: Installing Terminus
        uses: kopepasah/setup-pantheon-terminus@master
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
      - name: deployer
        env:
          pantheon_repo: "${{ secrets.PANTHEON_REPO_URL }}"
          pantheon_site_name: "${{ secrets.PANTHEON_SITE_NAME }}"
        run: |
          echo ${{ secrets.KNOWN_HOSTS }}
          git remote add pantheon $pantheon_repo
          git push pantheon HEAD:master
          commit_message=$(git log -1 --pretty=%B)
          terminus env:deploy $pantheon_site_name.dev --note="Automated deploy: $commit_message"
      - name: Validate composer
        run: composer validate
      - name: Install dependency
        run: composer install
      - name: Deploy the code
        run: |
          git remote add pantheon ${{ secrets.PANTHEON_REPO_URL }}
          git push pantheon master
      - name: Deployed status
        run: echo "Deployed ...."
