name: Deploy to Pantheon
run-name: Deploy to ${{ inputs.environment_name }} (@${{ github.actor }})
on:
  workflow_dispatch:
    inputs:
      environment_name:
        type: choice
        description: Which Pantheon environment to deploy to
        options:
          - dev
          - test
          - live
      deploy_message:
        type: string
      deploy_force:
        type: boolean
        default: false
        description: Force deployment even if there is overridden configuration on the target environment
      post_import_config:
        type: boolean
        default: true
        description: Import configuration after deployment
      post_db_update:
        type: boolean
        default: true
        description: Run DB updates after deployment
      clear_env_cache:
        type: boolean
        default: true
        description: Clear target environment cache
jobs:
  deploy:
    uses: kalwar/github-actions/.github/workflows/deploy_to_pantheon.yml@main
    secrets:
      TERMINUS_DOWNSTREAM_SSH_KEY: ${{ secrets.PANTHEON_PRIVATE_SSH_KEY }}
      TERMINUS_MACHINE_TOKEN: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
